### ISSUE TITLE
error in Z2UI5_TOOL_CL_APP_05 - fileupload

### ISSUE THREAD

**Issue by choper725** [abap2UI5/ext-app_tools#1]
![image](https://github.com/abap2UI5/demo-demos/assets/129428114/5777d4a0-c977-435b-9cfd-8527f57569f3)

getting this, got something to do with the timer i guess ??

**Comment by choper725** [comment]
imported again, getting this..

![image](https://github.com/abap2UI5/ext-app_tools/assets/129428114/16398ceb-e9b2-4638-a5f3-66d5b370666d)

making this change, fixed it for me..
![image](https://github.com/abap2UI5/ext-app_tools/assets/129428114/88aa200d-cdcc-41f0-ba41-a816bd123c42)

**Comment by oblomov-dev** [comment]
On my side the variable looks like this:
<img width="813" alt="image" src="https://github.com/abap2UI5/ext-app_tools/assets/102328295/5f40307b-ada8-4158-bc76-f23b8465c348">

Made some fixes there yesterday and when you update both (main repo + tools repo) i hope it will look the same on your client.

**Comment by choper725** [comment]
pulled again and now its fixed..
